openapi: 3.0.3
info:
  title: Portal Empleo API - Get Own Profile
  version: 1.0.0
  description: Endpoint for retrieving authenticated user's profile

servers:
  - url: http://localhost:5000
    description: Development server
  - url: https://api.portalempleo.com
    description: Production server

paths:
  /api/v1/users/me:
    get:
      tags:
        - Users
      summary: Get authenticated user's profile
      description: |
        Returns the profile of the currently authenticated user.
        Requires valid JWT access token in Authorization header.
        Extracts user ID from token's 'sub' claim.
      operationId: getOwnProfile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
              example:
                id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                email: "juan.perez@example.com"
                firstName: "Juan"
                lastName: "Pérez"
                phoneNumber: "+34612345678"
                dateOfBirth: "1995-03-15"
                role: "CANDIDATE"
                createdAt: "2026-02-01T10:00:00Z"
                updatedAt: "2026-02-04T14:30:00Z"
        '401':
          description: Unauthorized (missing or invalid token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missingToken:
                  value:
                    error: "Unauthorized"
                    message: "Token de autenticación no proporcionado."
                invalidToken:
                  value:
                    error: "Unauthorized"
                    message: "Token de autenticación inválido o expirado."
        '404':
          description: User not found (edge case if token valid but user deleted)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "UserNotFound"
                message: "Usuario no encontrado."

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT access token obtained from /auth/login or /auth/refresh"

  schemas:
    UserDto:
      type: object
      required:
        - id
        - email
        - firstName
        - lastName
        - phoneNumber
        - dateOfBirth
        - role
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: "User unique identifier"
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        email:
          type: string
          format: email
          description: "User email (immutable)"
          example: "juan.perez@example.com"
        firstName:
          type: string
          description: "User's first name"
          example: "Juan"
        lastName:
          type: string
          description: "User's last name"
          example: "Pérez"
        phoneNumber:
          type: string
          pattern: '^\+[1-9]\d{1,14}$'
          description: "Phone number (E.164 format)"
          example: "+34612345678"
        dateOfBirth:
          type: string
          format: date
          description: "User's date of birth (ISO 8601)"
          example: "1995-03-15"
        role:
          type: string
          enum: [CANDIDATE, COMPANY, ADMIN]
          description: "User role in the system"
          example: "CANDIDATE"
        createdAt:
          type: string
          format: date-time
          description: "Account creation timestamp (UTC)"
          example: "2026-02-01T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: "Last profile update timestamp (UTC)"
          example: "2026-02-04T14:30:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: "Error code (Unauthorized, UserNotFound)"
          example: "Unauthorized"
        message:
          type: string
          description: "Human-readable error message"
          example: "Token de autenticación no proporcionado."
