# CI/CD Pipeline - PortalEmpleo API

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  DOTNET_VERSION: '8.0.x'
  SONAR_PROJECT_KEY: 'PortalEmpleo'
  COVERAGE_THRESHOLD: 80

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: bin/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: |
          dotnet test \
            --no-restore \
            --verbosity normal \
            --collect:"XPlat Code Coverage" \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverageThreshold=${{ env.COVERAGE_THRESHOLD }} \
            /p:CoverageOutputFormat=opencover

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.opencover.xml

      - name: Check coverage threshold
        run: |
          echo "Coverage threshold: ${{ env.COVERAGE_THRESHOLD }}%"
          echo "If coverage is below threshold, the build will fail."

  quality:
    name: Quality Analysis
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          DEPSCAN_LICENSE: ${{ secrets.DEPENDENCY_LICENSE }}
        with:
          project: 'PortalEmpleo'
          format: 'HTML'
          out: 'dependency-check-report'
          scan: 'src/'

      - name: Upload security report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report
          path: dependency-check-report/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test, quality, security]
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish API
        run: |
          dotnet publish \
            --no-restore \
            --configuration Release \
            --output ./publish

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'portempleo-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [build, test, quality, security]
    if: always()

    steps:
      - name: Send notification
        run: |
          echo "=== Pipeline Status ==="
          echo "Build: ${{ needs.build.result }}"
          echo "Test: ${{ needs.test.result }}"
          echo "Quality: ${{ needs.quality.result }}"
          echo "Security: ${{ needs.security.result }}"
          echo "========================"

      - name: Slack Notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#deployments'
          text: 'CI/CD Pipeline failed!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
