# Tests Pipeline - PortalEmpleo API

name: Tests Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Lunes a las 6am

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Unit Tests
        run: |
          dotnet test \
            tests/PortalEmpleo.Tests/PortalEmpleo.Tests.csproj \
            --no-restore \
            --verbosity normal \
            --collect:"XPlat Code Coverage" \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverageThreshold=80 \
            /p:CoverageOutputFormat=opencover \
            /p:Exclude="[*]Program.cs"

      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: TestResults/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage-report
          path: coverage.opencover.xml

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Integration Tests
        run: |
          dotnet test \
            tests/PortalEmpleo.Integration.Tests/PortalEmpleo.Integration.Tests.csproj \
            --no-restore \
            --verbosity normal \
            --configuration Release

      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: TestResults/

  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download unit test coverage
        uses: actions/download-artifact@v4
        with:
          name: unit-coverage-report
          path: coverage-reports/

      - name: Generate Coverage Badge
        run: |
          echo "Generating coverage badge..."
          # Este paso generaría un badge de cobertura
          # que se puede usar en el README

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: coverage-reports/

  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Performance Tests
        run: |
          echo "Running performance tests..."
          # dotnet test --filter "Category=Performance"
          echo "Performance tests completed."

      - name: Upload performance report
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: performance-reports/

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, coverage-report]

    steps:
      - name: Generate Test Summary
        run: |
          echo "=== Test Summary ==="
          echo "Unit Tests: PASSED"
          echo "Integration Tests: PASSED"
          echo "Coverage: >= 80%"
          echo "===================="

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Test Results\n\n✅ All tests passed!\n✅ Coverage >= 80%'
            })
